[package]
name = "matching-engine"
version.workspace = true
edition.workspace = true

[dependencies]
uuid = { workspace = true}
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rust_decimal_macros = "1.40.0"